const catalog = window.KUROMICHI_CATALOG || {games:[],links:[]};
function element(tag,className,text){const el=document.createElement(tag);if(className)el.className=className;if(text)el.textContent=text;return el;}
function safeLink(value){try{const url=new URL(value,location.href);return ['http:','https:','file:'].includes(url.protocol)?url.href:'#';}catch{return '#';}}
const games=document.getElementById('game-list');
document.getElementById('game-count').textContent=catalog.games.length;document.getElementById('game-count').hidden=!catalog.games.length;
if(!catalog.games.length){const empty=element('div','empty');const copy=element('div');copy.append(element('h3','','ゲームは準備中です')); empty.append(element('span','empty-symbol','?'),copy);games.append(empty);}
catalog.games.forEach((game,i)=>{const a=element('a','card');a.href=game.local?'play.html?game='+encodeURIComponent(game.id):safeLink(game.url);if(!game.local){a.target='_blank';a.rel='noopener noreferrer';}const cover=element('div','card-cover');if(game.image){const img=element('img');img.src=safeLink(game.image);img.alt='';img.loading='lazy';cover.append(img);}else cover.textContent=String(i+1).padStart(2,'0');const body=element('div','card-body');body.append(element('span','tag',game.local?'ブラウザゲーム':'外部サイトで遊ぶ'),element('h3','',game.title));const action=element('div','card-action');action.append(element('span','','遊んでみる'),element('span','',game.local?'▶':'↗'));body.append(action);a.append(cover,body);games.append(a);});
const links=document.getElementById('link-list');document.getElementById('links').hidden=false;document.getElementById('links-nav').hidden=false;
catalog.links.forEach(link=>{const a=element('a','link-card');a.href=safeLink(link.url);a.target='_blank';a.rel='noopener noreferrer';const copy=element('div');copy.append(element('strong','',link.title),element('small','',link.description));a.append(copy,element('span','','↗'));links.append(a);});

for(const platform of [{name:'YouTube',hosts:['youtube.com','youtu.be']},{name:'Twitter（X）',hosts:['twitter.com','x.com']}]){const registered=catalog.links.some(link=>{try{const host=new URL(link.url).hostname.toLowerCase();return platform.hosts.some(domain=>host===domain||host.endsWith('.'+domain));}catch{return false;}});if(!registered){const card=element('div','link-card link-pending');card.append(element('strong','',platform.name),element('span','pending-label','準備中'));links.append(card);}}
