const catalog = window.KUROMICHI_CATALOG || {games:[],links:[]};
function element(tag,className,text){const el=document.createElement(tag);if(className)el.className=className;if(text)el.textContent=text;return el;}
function safeLink(value){try{const url=new URL(value,location.href);return ['http:','https:','file:'].includes(url.protocol)?url.href:'#';}catch{return '#';}}
const games=document.getElementById('game-list');
document.getElementById('game-count').textContent=catalog.games.length;
if(!catalog.games.length){const empty=element('div','empty');const copy=element('div');copy.append(element('h3','','最初のゲーム、ただいま準備中。'),element('p','','公開したゲームはここに並びます。次の「作ってみた」をお楽しみに！'));empty.append(element('span','empty-symbol','?'),copy);games.append(empty);}
catalog.games.forEach((game,i)=>{const a=element('a','card');a.href=game.local?'play.html?game='+encodeURIComponent(game.id):safeLink(game.url);if(!game.local){a.target='_blank';a.rel='noopener noreferrer';}const cover=element('div','card-cover');if(game.image){const img=element('img');img.src=safeLink(game.image);img.alt='';img.loading='lazy';cover.append(img);}else cover.textContent=String(i+1).padStart(2,'0');const body=element('div','card-body');body.append(element('span','tag',game.local?'ブラウザゲーム':'外部サイトで遊ぶ'),element('h3','',game.title),element('p','',game.description));const action=element('div','card-action');action.append(element('span','','遊んでみる'),element('span','',game.local?'▶':'↗'));body.append(action);a.append(cover,body);games.append(a);});
const links=document.getElementById('link-list');if(!catalog.links.length)links.append(element('p','link-empty','チャンネルや動画へのリンクは、準備ができ次第こちらに掲載します。'));
catalog.links.forEach(link=>{const a=element('a','link-card');a.href=safeLink(link.url);a.target='_blank';a.rel='noopener noreferrer';const copy=element('div');copy.append(element('strong','',link.title),element('small','',link.description));a.append(copy,element('span','','↗'));links.append(a);});
